2018-02-21 20:43:45,328 ERROR: Exception on /explore [GET] [in /Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/app/routes.py", line 51, in explore
    next_url=next_url, prev_url=prev_url)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/changyashin/Desktop/winter_vacation_project/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-02-21 20:45:58,420 INFO: Microblog startup [in /Users/changyashin/Desktop/winter_vacation_project/microblog/app/__init__.py:41]
2018-02-21 20:46:15,376 INFO: Microblog startup [in /Users/changyashin/Desktop/winter_vacation_project/microblog/app/__init__.py:41]
2018-04-22 17:04:42,878 INFO: Microblog startup [in /Users/changyashin/Desktop/for_internship/git/previous-works/microblog/app/__init__.py:41]
